version: '3.8'

services:
  # MongoDB 데이터베이스
  mongodb:
    image: mongo:7.0
    container_name: stock-simulator-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: stock_simulator
    volumes:
      - mongodb_data:/data/db
    networks:
      - stock-network

  # Flask 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-simulator-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/stock_simulator?authSource=admin
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - mongodb
    networks:
      - stock-network

  # React 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-simulator-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - stock-network
    stdin_open: true
    tty: true

networks:
  stock-network:
    driver: bridge

volumes:
  mongodb_data:
